# Generated by scripts/generate_storage.py; do not edit.
SOURCE_SHA256 = "52b6e32862159516a6b8918df5e1634ca3cd593426bf683e1b1f3a1f10928f84"
OPERATIONS = {'abort_upload': {'binary_request': False,
                  'binary_response': False,
                  'description': '网盘：Abort Upload。DELETE /api/v1/uploads/{uploadID}。每次传入用户 API '
                                 'Key；所需 '
                                 'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。本地文件正文使用 '
                                 'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 API '
                                 'Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                  'method': 'DELETE',
                  'path': '/api/v1/uploads/{uploadID}',
                  'schema': {'additionalProperties': False,
                             'properties': {'path': {'additionalProperties': False,
                                                     'properties': {'uploadID': {'format': 'uuid',
                                                                                 'type': 'string'}},
                                                     'required': ['uploadID'],
                                                     'type': 'object'}},
                             'required': ['path'],
                             'type': 'object'},
                  'scope': 'files:write',
                  'success': [204]},
 'complete_upload': {'binary_request': False,
                     'binary_response': False,
                     'description': '网盘：Complete Upload。POST '
                                    '/api/v1/uploads/{uploadID}/complete。每次传入用户 API Key；所需 '
                                    'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。本地文件正文使用 '
                                    'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 API '
                                    'Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                     'method': 'POST',
                     'path': '/api/v1/uploads/{uploadID}/complete',
                     'schema': {'additionalProperties': False,
                                'properties': {'body': {'additionalProperties': False,
                                                        'description': 'Finalizes the upload once; '
                                                                       'repeated completion is a '
                                                                       'conflict.',
                                                        'properties': {'parts': {'description': 'Required '
                                                                                                'and '
                                                                                                'non-empty '
                                                                                                'for '
                                                                                                'multipart '
                                                                                                'uploads; '
                                                                                                'ignored '
                                                                                                'for '
                                                                                                'local '
                                                                                                'and '
                                                                                                'single '
                                                                                                'uploads.',
                                                                                 'items': {'additionalProperties': False,
                                                                                           'properties': {'etag': {'minLength': 1,
                                                                                                                   'type': 'string'},
                                                                                                          'part_number': {'format': 'int32',
                                                                                                                          'maximum': 10000,
                                                                                                                          'minimum': 1,
                                                                                                                          'type': 'integer'}},
                                                                                           'required': ['part_number',
                                                                                                        'etag'],
                                                                                           'type': 'object'},
                                                                                 'type': 'array'}},
                                                        'type': 'object'},
                                               'path': {'additionalProperties': False,
                                                        'properties': {'uploadID': {'format': 'uuid',
                                                                                    'type': 'string'}},
                                                        'required': ['uploadID'],
                                                        'type': 'object'}},
                                'required': ['path', 'body'],
                                'type': 'object'},
                     'scope': 'files:write',
                     'success': [200]},
 'create_directory': {'binary_request': False,
                      'binary_response': False,
                      'description': '网盘：Create Directory。POST '
                                     '/api/v1/projects/{projectID}/directories。每次传入用户 API Key；所需 '
                                     'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。',
                      'method': 'POST',
                      'path': '/api/v1/projects/{projectID}/directories',
                      'schema': {'additionalProperties': False,
                                 'properties': {'body': {'additionalProperties': False,
                                                         'properties': {'name': {'minLength': 1,
                                                                                 'type': 'string'},
                                                                        'parent_id': {'default': '',
                                                                                      'description': 'Directory '
                                                                                                     'UUID; '
                                                                                                     'omitted '
                                                                                                     'or '
                                                                                                     'empty '
                                                                                                     'means '
                                                                                                     'project '
                                                                                                     'root.',
                                                                                      'type': 'string'}},
                                                         'required': ['name'],
                                                         'type': 'object'},
                                                'path': {'additionalProperties': False,
                                                         'properties': {'projectID': {'format': 'uuid',
                                                                                      'type': 'string'}},
                                                         'required': ['projectID'],
                                                         'type': 'object'}},
                                 'required': ['path', 'body'],
                                 'type': 'object'},
                      'scope': 'files:write',
                      'success': [201]},
 'create_download': {'binary_request': False,
                     'binary_response': False,
                     'description': '网盘：Create Download。POST '
                                    '/api/v1/nodes/{nodeID}/download。每次传入用户 API Key；所需 '
                                    'Scope：files:read，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。',
                     'method': 'POST',
                     'path': '/api/v1/nodes/{nodeID}/download',
                     'schema': {'additionalProperties': False,
                                'properties': {'path': {'additionalProperties': False,
                                                        'properties': {'nodeID': {'format': 'uuid',
                                                                                  'type': 'string'}},
                                                        'required': ['nodeID'],
                                                        'type': 'object'}},
                                'required': ['path'],
                                'type': 'object'},
                     'scope': 'files:read',
                     'success': [200]},
 'create_project': {'binary_request': False,
                    'binary_response': False,
                    'description': '网盘：Create Project。POST /api/v1/projects。每次传入用户 API Key；所需 '
                                   'Scope：projects:create，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。密钥须为 '
                                   'all_projects，用户须具备全局写入权限。',
                    'method': 'POST',
                    'path': '/api/v1/projects',
                    'schema': {'additionalProperties': False,
                               'properties': {'body': {'additionalProperties': False,
                                                       'properties': {'description': {'default': '',
                                                                                      'type': 'string'},
                                                                      'name': {'minLength': 1,
                                                                               'type': 'string'},
                                                                      'storage_backend_id': {'format': 'uuid',
                                                                                             'type': 'string'}},
                                                       'required': ['name', 'storage_backend_id'],
                                                       'type': 'object'}},
                               'required': ['body'],
                               'type': 'object'},
                    'scope': 'projects:create',
                    'success': [201]},
 'create_upload': {'binary_request': False,
                   'binary_response': False,
                   'description': '网盘：Create Upload。POST '
                                  '/api/v1/projects/{projectID}/uploads。每次传入用户 API Key；所需 '
                                  'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。本地文件正文使用 '
                                  'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 API '
                                  'Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                   'method': 'POST',
                   'path': '/api/v1/projects/{projectID}/uploads',
                   'schema': {'additionalProperties': False,
                              'properties': {'body': {'additionalProperties': False,
                                                      'description': 'Send the actual size '
                                                                     'explicitly; omission is '
                                                                     'treated as zero by the '
                                                                     'backend.',
                                                      'properties': {'filename': {'type': 'string'},
                                                                     'mime_type': {'default': 'application/octet-stream',
                                                                                   'type': 'string'},
                                                                     'overwrite': {'default': False,
                                                                                   'type': 'boolean'},
                                                                     'parent_id': {'default': '',
                                                                                   'description': 'Directory '
                                                                                                  'UUID; '
                                                                                                  'omitted '
                                                                                                  'or '
                                                                                                  'empty '
                                                                                                  'means '
                                                                                                  'project '
                                                                                                  'root.',
                                                                                   'type': 'string'},
                                                                     'size': {'default': 0,
                                                                              'format': 'int64',
                                                                              'maximum': 5497558138880,
                                                                              'minimum': 0,
                                                                              'type': 'integer'}},
                                                      'required': ['filename'],
                                                      'type': 'object'},
                                             'path': {'additionalProperties': False,
                                                      'properties': {'projectID': {'format': 'uuid',
                                                                                   'type': 'string'}},
                                                      'required': ['projectID'],
                                                      'type': 'object'}},
                              'required': ['path', 'body'],
                              'type': 'object'},
                   'scope': 'files:write',
                   'success': [201]},
 'delete_node': {'binary_request': False,
                 'binary_response': False,
                 'description': '网盘：Delete Node。DELETE /api/v1/nodes/{nodeID}。每次传入用户 API Key；所需 '
                                'Scope：files:delete，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。',
                 'method': 'DELETE',
                 'path': '/api/v1/nodes/{nodeID}',
                 'schema': {'additionalProperties': False,
                            'properties': {'path': {'additionalProperties': False,
                                                    'properties': {'nodeID': {'format': 'uuid',
                                                                              'type': 'string'}},
                                                    'required': ['nodeID'],
                                                    'type': 'object'}},
                            'required': ['path'],
                            'type': 'object'},
                 'scope': 'files:delete',
                 'success': [204]},
 'download_local_content': {'binary_request': False,
                            'binary_response': True,
                            'description': '网盘：Download Local Content。GET '
                                           '/api/v1/nodes/{nodeID}/content。每次传入用户 API Key；所需 '
                                           'Scope：files:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。本地文件正文使用 '
                                           'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL '
                                           '由客户端直接访问，不携带 API Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                            'method': 'GET',
                            'path': '/api/v1/nodes/{nodeID}/content',
                            'schema': {'additionalProperties': False,
                                       'properties': {'header': {'additionalProperties': False,
                                                                 'properties': {'Range': {'example': 'bytes=0-1048575',
                                                                                          'pattern': '^bytes=(?:[0-9]+-[0-9]*|-[0-9]+)$',
                                                                                          'type': 'string'}},
                                                                 'type': 'object'},
                                                      'path': {'additionalProperties': False,
                                                               'properties': {'nodeID': {'format': 'uuid',
                                                                                         'type': 'string'}},
                                                               'required': ['nodeID'],
                                                               'type': 'object'}},
                                       'required': ['path'],
                                       'type': 'object'},
                            'scope': 'files:read',
                            'success': [200, 206]},
 'get_node': {'binary_request': False,
              'binary_response': False,
              'description': '网盘：Get Node。GET /api/v1/nodes/{nodeID}。每次传入用户 API Key；所需 '
                             'Scope：files:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。',
              'method': 'GET',
              'path': '/api/v1/nodes/{nodeID}',
              'schema': {'additionalProperties': False,
                         'properties': {'path': {'additionalProperties': False,
                                                 'properties': {'nodeID': {'format': 'uuid',
                                                                           'type': 'string'}},
                                                 'required': ['nodeID'],
                                                 'type': 'object'}},
                         'required': ['path'],
                         'type': 'object'},
              'scope': 'files:read',
              'success': [200]},
 'get_project': {'binary_request': False,
                 'binary_response': False,
                 'description': '网盘：Get Project。GET /api/v1/projects/{projectID}。每次传入用户 API Key；所需 '
                                'Scope：projects:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。',
                 'method': 'GET',
                 'path': '/api/v1/projects/{projectID}',
                 'schema': {'additionalProperties': False,
                            'properties': {'path': {'additionalProperties': False,
                                                    'properties': {'projectID': {'format': 'uuid',
                                                                                 'type': 'string'}},
                                                    'required': ['projectID'],
                                                    'type': 'object'}},
                            'required': ['path'],
                            'type': 'object'},
                 'scope': 'projects:read',
                 'success': [200]},
 'head_local_content': {'binary_request': False,
                        'binary_response': False,
                        'description': '网盘：Head Local Content。HEAD '
                                       '/api/v1/nodes/{nodeID}/content。每次传入用户 API Key；所需 '
                                       'Scope：files:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。本地文件正文使用 '
                                       'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 '
                                       'API Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                        'method': 'HEAD',
                        'path': '/api/v1/nodes/{nodeID}/content',
                        'schema': {'additionalProperties': False,
                                   'properties': {'header': {'additionalProperties': False,
                                                             'properties': {'Range': {'example': 'bytes=0-1048575',
                                                                                      'pattern': '^bytes=(?:[0-9]+-[0-9]*|-[0-9]+)$',
                                                                                      'type': 'string'}},
                                                             'type': 'object'},
                                                  'path': {'additionalProperties': False,
                                                           'properties': {'nodeID': {'format': 'uuid',
                                                                                     'type': 'string'}},
                                                           'required': ['nodeID'],
                                                           'type': 'object'}},
                                   'required': ['path'],
                                   'type': 'object'},
                        'scope': 'files:read',
                        'success': [200]},
 'list_available_storage_backends': {'binary_request': False,
                                     'binary_response': False,
                                     'description': '网盘：List Available Storage Backends。GET '
                                                    '/api/v1/storage-backends。每次传入用户 API Key；所需 '
                                                    'Scope：projects:create，用户当前权限与密钥项目范围仍由上游校验。只读查询。密钥须为 '
                                                    'all_projects，用户须具备全局写入权限。',
                                     'method': 'GET',
                                     'path': '/api/v1/storage-backends',
                                     'schema': {'additionalProperties': False,
                                                'properties': {},
                                                'type': 'object'},
                                     'scope': 'projects:create',
                                     'success': [200]},
 'list_nodes': {'binary_request': False,
                'binary_response': False,
                'description': '网盘：List Nodes。GET /api/v1/projects/{projectID}/nodes。每次传入用户 API '
                               'Key；所需 Scope：files:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。',
                'method': 'GET',
                'path': '/api/v1/projects/{projectID}/nodes',
                'schema': {'additionalProperties': False,
                           'properties': {'path': {'additionalProperties': False,
                                                   'properties': {'projectID': {'format': 'uuid',
                                                                                'type': 'string'}},
                                                   'required': ['projectID'],
                                                   'type': 'object'},
                                          'query': {'additionalProperties': False,
                                                    'properties': {'parent_id': {'anyOf': [{'format': 'uuid',
                                                                                            'type': 'string'},
                                                                                           {'const': ''}]}},
                                                    'type': 'object'}},
                           'required': ['path'],
                           'type': 'object'},
                'scope': 'files:read',
                'success': [200]},
 'list_projects': {'binary_request': False,
                   'binary_response': False,
                   'description': '网盘：List Projects。GET /api/v1/projects。每次传入用户 API Key；所需 '
                                  'Scope：projects:read，用户当前权限与密钥项目范围仍由上游校验。只读查询。',
                   'method': 'GET',
                   'path': '/api/v1/projects',
                   'schema': {'additionalProperties': False, 'properties': {}, 'type': 'object'},
                   'scope': 'projects:read',
                   'success': [200]},
 'presign_upload_parts': {'binary_request': False,
                          'binary_response': False,
                          'description': '网盘：Presign Upload Parts。POST '
                                         '/api/v1/uploads/{uploadID}/parts/presign。每次传入用户 API '
                                         'Key；所需 '
                                         'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。本地文件正文使用 '
                                         'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 '
                                         'API Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                          'method': 'POST',
                          'path': '/api/v1/uploads/{uploadID}/parts/presign',
                          'schema': {'additionalProperties': False,
                                     'properties': {'body': {'additionalProperties': False,
                                                             'properties': {'part_numbers': {'items': {'format': 'int32',
                                                                                                       'maximum': 10000,
                                                                                                       'minimum': 1,
                                                                                                       'type': 'integer'},
                                                                                             'maxItems': 100,
                                                                                             'minItems': 1,
                                                                                             'type': 'array',
                                                                                             'uniqueItems': True}},
                                                             'required': ['part_numbers'],
                                                             'type': 'object'},
                                                    'path': {'additionalProperties': False,
                                                             'properties': {'uploadID': {'format': 'uuid',
                                                                                         'type': 'string'}},
                                                             'required': ['uploadID'],
                                                             'type': 'object'}},
                                     'required': ['path', 'body'],
                                     'type': 'object'},
                          'scope': 'files:write',
                          'success': [200]},
 'update_node': {'binary_request': False,
                 'binary_response': False,
                 'description': '网盘：Update Node。PATCH /api/v1/nodes/{nodeID}。每次传入用户 API Key；所需 '
                                'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。',
                 'method': 'PATCH',
                 'path': '/api/v1/nodes/{nodeID}',
                 'schema': {'additionalProperties': False,
                            'properties': {'body': {'additionalProperties': False,
                                                    'minProperties': 1,
                                                    'properties': {'name': {'type': 'string'},
                                                                   'parent_id': {'description': 'Empty '
                                                                                                'string '
                                                                                                'moves '
                                                                                                'the '
                                                                                                'node '
                                                                                                'to '
                                                                                                'the '
                                                                                                'project '
                                                                                                'root.',
                                                                                 'type': 'string'}},
                                                    'type': 'object'},
                                           'path': {'additionalProperties': False,
                                                    'properties': {'nodeID': {'format': 'uuid',
                                                                              'type': 'string'}},
                                                    'required': ['nodeID'],
                                                    'type': 'object'}},
                            'required': ['path', 'body'],
                            'type': 'object'},
                 'scope': 'files:write',
                 'success': [200]},
 'upload_local_content': {'binary_request': True,
                          'binary_response': False,
                          'description': '网盘：Upload Local Content。PUT '
                                         '/api/v1/uploads/{uploadID}/content。每次传入用户 API Key；所需 '
                                         'Scope：files:write，用户当前权限与密钥项目范围仍由上游校验。会执行写入、删除或签名操作；不自动重试。本地文件正文使用 '
                                         'Base64，单次最多 10 MiB；大文件下载使用 Range。外部预签名 URL 由客户端直接访问，不携带 '
                                         'API Key。创建上传时明确提供真实 size；完成上传不保证幂等。',
                          'method': 'PUT',
                          'path': '/api/v1/uploads/{uploadID}/content',
                          'schema': {'additionalProperties': False,
                                     'properties': {'body_base64': {'contentEncoding': 'base64',
                                                                    'description': '原始文件的标准 '
                                                                                   'Base64；最多 10 '
                                                                                   'MiB，空文件传空字符串。',
                                                                    'maxLength': 13981016,
                                                                    'type': 'string'},
                                                    'path': {'additionalProperties': False,
                                                             'properties': {'uploadID': {'format': 'uuid',
                                                                                         'type': 'string'}},
                                                             'required': ['uploadID'],
                                                             'type': 'object'}},
                                     'required': ['path', 'body_base64'],
                                     'type': 'object'},
                          'scope': 'files:write',
                          'success': [204]}}
