"""Compile the supplied OpenAPI into a fingerprinted, offline plugin contract."""

import argparse
import hashlib
import json
from pathlib import Path
from pprint import pformat

ROOT = Path(__file__).resolve().parents[1]


def compile_contract(source):
    document = json.loads(source)

    def expand(value):
        if isinstance(value, list):
            return [expand(item) for item in value]
        if not isinstance(value, dict):
            return value
        if "$ref" in value:
            prefix = "#/components/schemas/"
            assert value["$ref"].startswith(prefix)
            return expand(
                {
                    **document["components"]["schemas"][value["$ref"][len(prefix) :]],
                    **{k: v for k, v in value.items() if k != "$ref"},
                }
            )
        return {key: expand(item) for key, item in value.items()}

    operations = {}
    for path, methods in document["paths"].items():
        for method, op in methods.items():
            # Fail closed: only explicitly documented account-user operations are exposed.
            auth = "AccountAPIKey"
            if {auth: []} not in op.get("security", []) or op.get(
                "x-access"
            ) != "登录；资源归属限制见接口说明":
                continue
            # Handler prefix is stable, readable, and unique in this contract.
            name = op["operationId"].split("_api_")[0]
            assert name not in operations, f"Duplicate tool ID: {name}"
            schema = {"type": "object", "properties": {}, "additionalProperties": False}
            required = []
            for location in ("path", "query"):
                params = [p for p in op.get("parameters", []) if p["in"] == location]
                if not params:
                    continue
                group = {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {p["name"]: expand(p["schema"]) for p in params},
                }
                needed = [p["name"] for p in params if p.get("required")]
                if needed:
                    group["required"] = needed
                    required.append(location)
                schema["properties"][location] = group
            body = op.get("requestBody", {})
            content = body.get("content", {})
            if "application/json" in content:
                schema["properties"]["body"] = expand(content["application/json"]["schema"])
                if body.get("required"):
                    required.append("body")
            else:
                assert not content, (path, content)
            if required:
                schema["required"] = required
            description = (
                f"{op['summary']}。{method.upper()} {path}。"
                f"权限：{op.get('x-access', '由上游判断')}。"
                + (
                    "只读查询。"
                    if method == "get"
                    else "会执行写入或状态操作；调用前确认目标和参数，不自动重试。"
                )
                + f"调用方每次提供 {auth}，仅作为上游 X-API-Key 请求头。\n"
                + op.get("description", "")
            )
            if path.startswith("/api/projects/{project_id}/"):
                description += "\n如 body 含 project_id，必须与 path.project_id 相同。"
            if path == "/api/shop/orders":
                description += "\nrequest_id 为业务幂等键，重试同一订单必须保留原值。金额单位为分。"
            operations[name] = {
                "method": method.upper(),
                "path": path,
                "auth": auth,
                "schema": schema,
                "description": description,
                "success": [int(c) for c in op["responses"] if c.isdigit() and 200 <= int(c) < 300],
            }
    return operations


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = (ROOT / "plugins/csa/docs/openapi.json").read_bytes()
    operations = compile_contract(source)
    output = (
        "# Generated by scripts/generate_csa.py; do not edit.\n"
        f'SOURCE_SHA256 = "{hashlib.sha256(source).hexdigest()}"\n'
        + "OPERATIONS = "
        + pformat(operations, width=100, sort_dicts=True)
        + "\n"
    )
    target = ROOT / "plugins/csa/contract.py"
    if args.check:
        if target.read_text() != output:
            raise SystemExit("CSA contract is stale; run uv run python scripts/generate_csa.py")
    else:
        target.write_text(output)
    print(f"CSA contract: {len(operations)} tools")


if __name__ == "__main__":
    main()
